ALTER TABLE "person" ALTER COLUMN "name" SET STATISTICS 10000;
ALTER TABLE "person" ALTER COLUMN "id" SET STATISTICS 10000;
ALTER MATERIALIZED VIEW "actors_info" ALTER COLUMN "person_role_id" SET STATISTICS 10000;
ALTER MATERIALIZED VIEW "actors_info" ALTER COLUMN "person_id" SET STATISTICS 10000;
ALTER MATERIALIZED VIEW "actors_info" ALTER COLUMN "movie_id" SET STATISTICS 10000;
ALTER TABLE "cast_info" ALTER COLUMN "role_id" SET STATISTICS 10000;
ALTER TABLE "cast_info" ALTER COLUMN "movie_id" SET STATISTICS 10000;
ANALYZE;



